feat: add DatabaseSize check
instride-ch/pimcore-monitor pull request #4
Opened 2023-04-06 11:39 UTC by alexloetscher95

resolves https://github.com/w-vision/PimcoreMonitorBundle/issues/2

Default warning threshold: 512 MB
Default failure threshold: 1024 MB

Ok?

2023-04-07 07:24 UTC, aarongerig requested changes
@alexloetscher95 Some minor code style changes, but other than that OK.
Are 512MB / 1024MB reasonable size thresholds?

2023-04-07 07:24 UTC, aarongerig commented on src/PimcoreMonitorBundle/Check/DatabaseSize.php
> +        {
```suggestion
        if (\is_array($size) && isset($size[0]['size'])) {
```

2023-04-07 07:24 UTC, aarongerig commented on src/PimcoreMonitorBundle/Check/DatabaseSize.php
> +            return (int)$size[0]['size'];
```suggestion
            return (int) $size[0]['size'];
```

2023-04-07 07:24 UTC, aarongerig commented on src/PimcoreMonitorBundle/Check/DatabaseSize.php
> +        return new Success(sprintf('Database size is %s', \formatBytes($size)), $data);
```suggestion
        return new Success(\sprintf('Database size is %s', \formatBytes($size)), $data);
```

2023-04-11 10:58 UTC, alexloetscher95 commented
> @alexloetscher95 Some minor code style changes, but other than that OK. Are 512MB / 1024MB reasonable size thresholds?

@aarongerig I think that we should continually test and adapt this

2023-04-11 11:13 UTC, aarongerig commented
@alexloetscher95 Code looks fine now, thanks!
What do you think about setting the warning threshold to something around 920MB, which would be around 90% of 1024MB  (error threshold). Otherwise I'm afraid that we get a lot of DBs with warnings, even though we don't need to take action.

2023-04-11 11:14 UTC, aarongerig approved these changes

2023-04-11 11:19 UTC, alexloetscher95 commented
@aarongerig yeah. 90% makes much more sense :/ 
Changed it to 920 MB (approx. 90%) and will merge it immediately

2023-04-11 11:19 UTC, merged