Feat/extend api metadata
instride-ch/pimcore-monitor pull request #6
Opened 2023-11-20 09:37 UTC by dvonrohr

2023-11-20 12:31 UTC, aarongerig requested changes
@dvonrohr Some minor changes as discussed.

2023-11-20 12:31 UTC, aarongerig commented on docs/00-installation-configuration.md
> +        instance_environment: 'Production'
I would use lower case and shortened keywords as example values.
```suggestion
        # Environment description for the instance (e.g. "prod", "test", "dev"). 
        instance_environment: 'prod'
```

2023-11-20 12:31 UTC, aarongerig commented on src/PimcoreMonitorBundle/Command/HealthReportCommand.php
> +        $projectId = $this->getInstanceId();
I think we should stick to the old name of "instance ID" nonetheless.
```suggestion
        $instanceId = $this->getInstanceId();
```

2023-11-20 12:31 UTC, aarongerig commented on src/PimcoreMonitorBundle/Command/HealthReportCommand.php
> +        if (null === $projectId) {
```suggestion
        if (null === $instanceId) {
```

2023-11-20 12:31 UTC, aarongerig commented on src/PimcoreMonitorBundle/Command/HealthReportCommand.php
> +                    'project_id'=> $projectId,
```suggestion
                    'instance_id'=> $instanceId,
```

2023-11-20 12:31 UTC, aarongerig commented on src/PimcoreMonitorBundle/DependencyInjection/Configuration.php
> +                ->end()
Here I would add a default value of `prod`.

2023-11-23 10:29 UTC, aarongerig requested changes

2023-11-23 10:29 UTC, aarongerig commented on src/PimcoreMonitorBundle/DependencyInjection/Configuration.php
> +                    ->info('Environment for project')
```suggestion
                    ->info('The name of the environment in which the application is running in.')
```

2023-11-23 10:29 UTC, aarongerig commented on src/PimcoreMonitorBundle/Command/HealthReportCommand.php
> +
Not necessary, as the property can never be empty at this point.

```suggestion
```

2023-11-23 10:29 UTC, aarongerig commented on src/PimcoreMonitorBundle/Command/HealthReportCommand.php
> +                    'instance_id'=> $instanceId,
```suggestion
                    'instance_id' => $instanceId,
```

2023-11-24 13:23 UTC, aarongerig approved these changes

2024-05-03 14:10 UTC, dvonrohr commented
The changes from this pull request have been successfully integrated into the main branch. Closing this pull request now.

2024-05-03 14:10 UTC, closed without merging